version: '3'
services:
  pig-ui:
    build:
      context: .
    restart: always
    container_name: manager-ui
    image: manager-ui
    networks:
      - yifan
    ports:
      - 80:80

# 加入到后端网络 docker network ls   查看
networks:
  yifan:
